=== IliesBenmansour/NFP212/projet-court/src/allumettes/deroulement.dtd
<!ELEMENT deroulement (coup*, (gagnant | triche))>

<!ELEMENT coup EMPTY>
<!ATTLIST coup
    numero NMTOKEN #REQUIRED
    joueur CDATA   #REQUIRED
    prises NMTOKEN #REQUIRED>

<!ELEMENT gagnant EMPTY>
<!ATTLIST gagnant nom CDATA #REQUIRED>

<!ELEMENT triche EMPTY>
<!ATTLIST triche joueur CDATA #REQUIRED>

=== IliesBenmansour/NFP212/projet-court/src/deroulement.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE deroulement SYSTEM "src/allumettes/deroulement.dtd">
<deroulement>
  <coup joueur="Xavier" numero="1" prises="2"/>
  <coup joueur="Ordinateur" numero="2" prises="3"/>
  <coup joueur="Xavier" numero="3" prises="3"/>
  <coup joueur="Ordinateur" numero="4" prises="3"/>
  <coup joueur="Xavier" numero="5" prises="1"/>
  <coup joueur="Ordinateur" numero="6" prises="1"/>
  <gagnant nom="Xavier"/>
</deroulement>
